version: "3.9"

services:
  server-fedora:
    build: .
    container_name: fedora-prueba
    working_dir: /home/script
    volumes:
      - ../../dfs:/home/script:z
    tty: true
    command: tail -f /dev/null
