version: "3.9"

services:
  server-ubuntu:
    build: .
    container_name: ubuntu-prueba
    working_dir: /home/script
    tty: true

    # Necesario para systemd dentro del contenedor
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp

    # TODOS los volúmenes juntos en una sola sección:
    volumes:
      - ../../dfs:/home/script:z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro