#!/usr/bin/node
import list from "./list.mjs";
import update from "./update.mjs";
import search from "./search.mjs";
import superUser from "./util/superUser.js";
import printHelp from "./util/printHelp.mjs";
import printSection from "./util/printSection.mjs";
import text from "./text/dnf.json" with { type: "json" };
import getPackageManager from "./util/getPackageManager.mjs";


const commands = await getPackageManager();

if (!commands) {
  printSection("red", text.error1);
  process.exit(1);
}

switch (process.argv[2]) {
  case "update":
    superUser();
    await update(commands, process.argv[3], process.argv[4]);
    break;
  case "search":
    await search(commands, process.argv[3], process.argv[4]);
    break;
  case "list":
    await list(commands, process.argv[3]);
    break;
  default:
    printSection("red",text.error2);
    printHelp(text.help);
    break;
}
