version: "3.9"

services:
  server-debian:
    build: node:22-bookworm-slim
    container_name: debian-prueba
    working_dir: /home/script
    volumes:
      - ../../dfs:/home/script:z
    tty: true
    command: tail -f /dev/null
    
