#!/usr/bin/node
import update from "./update.mjs";
import search from "./search.mjs";
import printHelp from "./util/printHelp.mjs";
import superUser from "./util/superUser.js";
import printSection from "./util/printSection.mjs";
import text from "./text/dnf.json" with { type: "json" };
import getPackageManager from "./util/getPackageManager.mjs";

const commands = await getPackageManager();

switch (process.argv[2]) {
  case "update":
    superUser();
    await update(commands, process.argv[3], process.argv[4]);
    break;
  case "search":
    await search(commands, process.argv[3], process.argv[4]);
    break;
  default:
    printSection("red",text.error);
    printHelp(text.help);
    break;
}
